name: ai_citizen_helpline
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.0  # or the latest version

  cupertino_icons: ^1.0.2
  http: ^1.3.0
  animated_text_kit: ^4.2.2
  google_fonts: ^5.1.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.1.7
  google_maps_flutter: ^2.2.0
  speech_to_text: ^6.3.0
  flutter_tts: ^3.8.1
  flutter_svg: ^2.0.9
  audioplayers: ^6.4.0
  geolocator: ^8.0.0
  flutter_phone_direct_caller: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  url_launcher: ^6.1.10

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/phone_ring.mp3

